"use client";

import Link from "next/link";
import { useState, type ChangeEvent, type ReactNode } from "react";
import { BrandMark } from "../components/brand-mark";
import { ArrowRight, FileText, Lock, MapPin, Shield } from "../components/icons";

const steps = ["Sobre o fato", "Onde aconteceu", "Quando aconteceu", "Identificação", "Anexos e revisão"];
type FormData = { category: string; description: string; address: string; district: string; reference: string; date: string; time: string; urgency: string; anonymous: boolean; name: string; phone: string; email: string; files: string[] };
const initial: FormData = { category: "", description: "", address: "", district: "", reference: "", date: "", time: "", urgency: "", anonymous: true, name: "", phone: "", email: "", files: [] };
const inputClass = "mt-2 w-full rounded-lg border border-slate-300 bg-white px-3.5 py-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-[#0c766d] focus:ring-2 focus:ring-[#0c766d]/15";

export function ReportFlow() {
  const [step, setStep] = useState(0); const [data, setData] = useState<FormData>(initial); const [error, setError] = useState(""); const [sent, setSent] = useState(false); const [copied, setCopied] = useState(false);
  const protocol = "VTX-2026-8F4D"; const trackingCode = "K7P9-42M";
  const update = (key: keyof FormData, value: string | boolean | string[]) => setData((current) => ({ ...current, [key]: value }));
  const validate = () => { if (step === 0 && (!data.category || data.description.trim().length < 10 || !data.urgency)) return "Informe o tipo, uma descrição com pelo menos 10 caracteres e o nível de urgência."; if (step === 1 && (!data.address.trim() || !data.district.trim())) return "Informe o endereço e o bairro aproximados."; if (step === 2 && !data.date) return "Informe ao menos a data aproximada do ocorrido."; if (step === 3 && !data.anonymous && !data.name.trim()) return "Informe seu nome ou escolha permanecer anônimo."; return ""; };
  const next = () => { const message = validate(); if (message) { setError(message); return; } setError(""); if (step === steps.length - 1) setSent(true); else setStep((value) => value + 1); };
  const addFiles = (event: ChangeEvent<HTMLInputElement>) => update("files", Array.from(event.target.files ?? []).map((file) => file.name));
  const copyProtocol = async () => { await navigator.clipboard?.writeText(protocol); setCopied(true); };
  if (sent) return <SuccessScreen protocol={protocol} trackingCode={trackingCode} copied={copied} onCopy={copyProtocol} />;
  return <main className="min-h-screen bg-[#f4f7f8] text-[#102b42]"><Header /><div className="mx-auto max-w-4xl px-5 py-9 sm:px-8 sm:py-12"><Link href="/" className="text-sm font-semibold text-[#0c766d] hover:text-[#092940]">← Voltar ao início</Link><div className="mt-7"><p className="text-xs font-bold tracking-[.16em] text-[#0c766d]">NOVA DENÚNCIA</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Registre uma informação</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Preencha o que souber. Nesta versão, o envio é uma simulação e nenhuma informação será armazenada.</p></div><Progress step={step} /><form onSubmit={(event) => { event.preventDefault(); next(); }} className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><div className="mb-7 border-b border-slate-200 pb-5"><p className="text-xs font-bold tracking-[.14em] text-[#0c766d]">ETAPA {step + 1} DE {steps.length}</p><h2 className="mt-1 text-2xl font-bold">{steps[step]}</h2></div>{step === 0 && <FactStep data={data} update={update} />}{step === 1 && <LocationStep data={data} update={update} />}{step === 2 && <WhenStep data={data} update={update} />}{step === 3 && <IdentityStep data={data} update={update} />}{step === 4 && <ReviewStep data={data} onFiles={addFiles} />}{error && <p role="alert" className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}<div className="mt-8 flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:justify-between"><button type="button" onClick={() => { setError(""); setStep((value) => Math.max(0, value - 1)); }} disabled={step === 0} className="min-h-11 rounded-lg px-4 text-sm font-semibold text-slate-600 disabled:cursor-not-allowed disabled:opacity-40">Voltar</button><button type="submit" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#0c766d] px-5 text-sm font-bold text-white transition hover:bg-[#095f58]">{step === steps.length - 1 ? "Simular envio" : "Continuar"} <ArrowRight /></button></div></form></div></main>;
}
function Header() { return <header className="bg-[#092940]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8 lg:px-10"><BrandMark /><span className="hidden text-sm font-medium text-slate-300 sm:block">Canal Seguro GCMJP</span></div></header>; }
function Progress({ step }: { step: number }) { return <ol aria-label="Progresso do formulário" className="mt-8 grid grid-cols-5 gap-1">{steps.map((label, index) => <li key={label} className="min-w-0"><div className={`h-1.5 rounded-full ${index <= step ? "bg-[#0c766d]" : "bg-slate-200"}`} /><span className={`mt-2 hidden text-xs font-medium sm:block ${index === step ? "text-[#0c766d]" : "text-slate-500"}`}>{index + 1}. {label}</span><span className="mt-2 block text-center text-xs font-bold text-[#0c766d] sm:hidden">{index + 1}</span></li>)}</ol>; }
function Label({ children, required = false }: { children: ReactNode; required?: boolean }) { return <label className="block text-sm font-semibold text-slate-700">{children}{required && <span className="ml-1 text-[#0c766d]">*</span>}</label>; }
function FactStep({ data, update }: Props) { return <div className="grid gap-6"><div><Label required>Tipo de informação ou ocorrência</Label><select value={data.category} onChange={(e) => update("category", e.target.value)} className={inputClass}><option value="">Selecione uma opção</option><option>Segurança urbana</option><option>Espaço público</option><option>Patrimônio municipal</option><option>Ordem e convivência</option><option>Outro</option></select></div><div><Label required>Descrição do fato</Label><textarea value={data.description} onChange={(e) => update("description", e.target.value)} rows={6} className={inputClass} placeholder="Conte o que aconteceu e inclua detalhes que possam ajudar na compreensão da situação." /><p className="mt-2 text-xs text-slate-500">Mínimo de 10 caracteres.</p></div><fieldset><legend className="text-sm font-semibold text-slate-700">Nível de urgência <span className="text-[#0c766d]">*</span></legend><div className="mt-3 grid gap-3 sm:grid-cols-3">{[["Baixa", "Sem risco imediato"], ["Média", "Requer atenção"], ["Alta", "Situação urgente"]].map(([value, detail]) => <label key={value} className={`cursor-pointer rounded-lg border p-3 text-sm transition ${data.urgency === value ? "border-[#0c766d] bg-[#d8f1ed]" : "border-slate-200 hover:border-slate-300"}`}><input type="radio" name="urgency" value={value} checked={data.urgency === value} onChange={(e) => update("urgency", e.target.value)} className="sr-only" /><span className="block font-bold">{value}</span><span className="mt-1 block text-xs text-slate-600">{detail}</span></label>)}</div></fieldset></div>; }
type Props = { data: FormData; update: (key: keyof FormData, value: string | boolean | string[]) => void };
function LocationStep({ data, update }: Props) { return <div className="grid gap-6"><div className="grid gap-5 sm:grid-cols-2"><div><Label required>Endereço aproximado</Label><input value={data.address} onChange={(e) => update("address", e.target.value)} className={inputClass} placeholder="Rua, avenida ou local" /></div><div><Label required>Bairro</Label><input value={data.district} onChange={(e) => update("district", e.target.value)} className={inputClass} placeholder="Ex.: Manaíra" /></div></div><div><Label>Ponto de referência ou complemento</Label><input value={data.reference} onChange={(e) => update("reference", e.target.value)} className={inputClass} placeholder="Ex.: próximo a..., em frente a..." /></div><div><p className="text-sm font-semibold text-slate-700">Localização no mapa</p><div className="mt-2 flex min-h-52 flex-col items-center justify-center rounded-xl border border-dashed border-[#0c766d]/40 bg-[#d8f1ed]/40 px-6 text-center"><span className="grid size-11 place-items-center rounded-full bg-white text-[#0c766d] shadow-sm"><MapPin /></span><p className="mt-3 font-semibold">Mapa disponível em breve</p><p className="mt-1 max-w-sm text-sm leading-6 text-slate-600">Esta área está preparada para a seleção precisa do local na próxima integração.</p></div></div></div>; }
function WhenStep({ data, update }: Props) { return <div className="grid gap-6 sm:grid-cols-2"><div><Label required>Data aproximada</Label><input type="date" value={data.date} onChange={(e) => update("date", e.target.value)} className={inputClass} /></div><div><Label>Horário aproximado</Label><input type="time" value={data.time} onChange={(e) => update("time", e.target.value)} className={inputClass} /></div><p className="sm:col-span-2 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-600">Caso não saiba o horário exato, deixe o campo em branco ou informe a informação aproximada na descrição.</p></div>; }
function IdentityStep({ data, update }: Props) { return <div className="grid gap-6"><label className="flex cursor-pointer gap-3 rounded-xl border border-[#0c766d]/25 bg-[#d8f1ed]/50 p-4"><input type="checkbox" checked={data.anonymous} onChange={(e) => update("anonymous", e.target.checked)} className="mt-0.5 size-4 accent-[#0c766d]" /><span><span className="block font-bold">Desejo permanecer anônimo</span><span className="mt-1 block text-sm leading-6 text-slate-600">Não informe dados pessoais se quiser realizar um envio anônimo.</span></span></label>{!data.anonymous && <div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label required>Nome</Label><input value={data.name} onChange={(e) => update("name", e.target.value)} className={inputClass} placeholder="Seu nome completo" /></div><div><Label>Telefone</Label><input type="tel" value={data.phone} onChange={(e) => update("phone", e.target.value)} className={inputClass} placeholder="(83) 00000-0000" /></div><div><Label>E-mail</Label><input type="email" value={data.email} onChange={(e) => update("email", e.target.value)} className={inputClass} placeholder="voce@exemplo.com" /></div></div>}</div>; }
function ReviewStep({ data, onFiles }: { data: FormData; onFiles: (event: ChangeEvent<HTMLInputElement>) => void }) { return <div className="grid gap-6"><div><p className="text-sm font-semibold text-slate-700">Fotos e vídeos</p><label className="mt-2 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-slate-300 px-5 py-8 text-center transition hover:border-[#0c766d] hover:bg-[#d8f1ed]/30"><FileText /><span className="mt-3 font-semibold">Selecionar arquivos</span><span className="mt-1 text-sm text-slate-600">Fotos ou vídeos que ajudem a contextualizar o relato.</span><input type="file" multiple accept="image/*,video/*" onChange={onFiles} className="sr-only" /></label>{data.files.length > 0 && <ul className="mt-3 space-y-1 text-sm text-slate-600">{data.files.map((file) => <li key={file}>• {file}</li>)}</ul>}</div><div className="rounded-xl bg-slate-50 p-5"><p className="font-bold">Revise antes de enviar</p><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><ReviewItem label="Tipo" value={data.category || "Não informado"} /><ReviewItem label="Urgência" value={data.urgency || "Não informada"} /><ReviewItem label="Local" value={[data.address, data.district].filter(Boolean).join(" — ") || "Não informado"} /><ReviewItem label="Identificação" value={data.anonymous ? "Envio anônimo" : data.name || "Não informada"} /></dl></div><p className="flex gap-2 text-xs leading-5 text-slate-500"><Lock /> Esta é uma demonstração local. Nenhuma informação será enviada ou armazenada.</p></div>; }
function ReviewItem({ label, value }: { label: string; value: string }) { return <div><dt className="text-slate-500">{label}</dt><dd className="mt-0.5 font-semibold text-slate-700">{value}</dd></div>; }
function SuccessScreen({ protocol, trackingCode, copied, onCopy }: { protocol: string; trackingCode: string; copied: boolean; onCopy: () => void }) { return <main className="min-h-screen bg-[#f4f7f8] text-[#102b42]"><Header /><div className="mx-auto flex max-w-2xl px-5 py-12 sm:py-20"><section className="w-full rounded-2xl bg-white p-6 text-center shadow-sm ring-1 ring-slate-200 sm:p-10"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[#d8f1ed] text-[#0c766d]"><Shield /></span><p className="mt-6 text-xs font-bold tracking-[.16em] text-[#0c766d]">SIMULAÇÃO CONCLUÍDA</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Informação registrada</h1><p className="mt-3 text-sm leading-6 text-slate-600">Este é um resultado demonstrativo: nenhum dado foi enviado ou salvo nesta etapa.</p><div className="mt-8 rounded-xl bg-[#092940] p-5 text-left text-white"><p className="text-xs font-bold tracking-[.14em] text-teal-200">PROTOCOLO</p><p className="mt-2 text-2xl font-bold tracking-wider">{protocol}</p><button type="button" onClick={onCopy} className="mt-4 rounded-lg bg-white/10 px-3 py-2 text-sm font-semibold hover:bg-white/20">{copied ? "Protocolo copiado" : "Copiar protocolo"}</button><p className="mt-6 text-xs font-bold tracking-[.14em] text-teal-200">CÓDIGO DE ACOMPANHAMENTO</p><p className="mt-2 text-xl font-bold tracking-wider">{trackingCode}</p></div><p className="mt-6 rounded-lg bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900">Guarde o protocolo e o código de acompanhamento. Eles serão necessários para consultar o andamento quando o serviço estiver conectado.</p><Link href="/" className="mt-8 inline-flex min-h-11 items-center justify-center rounded-lg bg-[#0c766d] px-5 text-sm font-bold text-white hover:bg-[#095f58]">Voltar à página inicial</Link></section></div></main>; }
