import { requireAdmin } from "../../../lib/auth/require-admin";
import { createAdminClient } from "../../../lib/supabase/admin";
import { createUnit,removeMember,saveMember } from "./actions";

export default async function UnitsPage(){
 await requireAdmin();const admin=createAdminClient();
 const [{data:units},{data:members},{data:profiles}]=await Promise.all([
  admin.from("vortex_units").select("*").order("name"),
  admin.from("vortex_unit_members").select("unit_id,profile_id,member_role"),
  admin.from("vortex_profiles").select("id,full_name,role,active,functional_title").eq("active",true).in("role",["COORDENADOR","OPERADOR"]).order("full_name")
 ]);
 const profileMap=new Map((profiles??[]).map(p=>[p.id,p]));
 return <div className="max-w-6xl"><p className="text-xs font-bold tracking-[.16em] text-[#0c766d]">ESTRUTURA OPERACIONAL</p><h1 className="mt-2 text-3xl font-bold">Grupamentos</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Cadastre os grupamentos e vincule seus coordenadores e inspetores. O sistema não direciona denúncias automaticamente: a definição do grupamento é feita manualmente pela Diretoria Operacional na Triagem Geral.</p>
 <section className="mt-7 grid gap-4 lg:grid-cols-2">{(units??[]).map(unit=>{const unitMembers=(members??[]).filter(m=>m.unit_id===unit.id);return <article key={unit.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div><h2 className="text-lg font-bold">{unit.name}</h2><p className="mt-1 text-xs font-bold text-[#0c766d]">{unit.code}</p></div><p className="mt-3 text-sm leading-6 text-slate-600">{unit.description||"Sem descrição."}</p><div className="mt-4 grid gap-2">{unitMembers.length===0?<p className="text-sm text-slate-500">Nenhum servidor vinculado.</p>:unitMembers.map(m=>{const p=profileMap.get(m.profile_id);return <div key={m.profile_id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-3"><div><p className="text-sm font-bold">{p?.full_name||"Usuário"}</p><p className="text-xs text-slate-500">{m.member_role==="COORDENADOR"?"Coordenador":"Inspetor/atendente"}{p?.functional_title?` · ${p.functional_title}`:""}</p></div><form action={removeMember}><input type="hidden" name="unitId" value={unit.id}/><input type="hidden" name="profileId" value={m.profile_id}/><button className="text-xs font-bold text-red-700">Remover</button></form></div>})}</div>
 <form action={saveMember} className="mt-4 grid gap-2 border-t border-slate-100 pt-4 sm:grid-cols-2"><input type="hidden" name="unitId" value={unit.id}/><select name="memberRole" className="rounded-lg border border-slate-300 p-2.5 text-sm"><option value="COORDENADOR">Coordenador</option><option value="INSPETOR">Inspetor/atendente</option></select><select name="profileId" required className="rounded-lg border border-slate-300 p-2.5 text-sm"><option value="">Selecionar usuário</option>{(profiles??[]).map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select><button className="rounded-lg bg-[#0c766d] px-3 py-2 text-sm font-bold text-white sm:col-span-2">Adicionar/atualizar vínculo</button></form></article>})}</section>
 <form action={createUnit} className="mt-8 grid gap-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Novo grupamento</h2><div className="grid gap-3 sm:grid-cols-2"><input required name="name" maxLength={120} placeholder="Nome do grupamento" className="rounded-lg border border-slate-300 p-3 text-sm"/><input required name="code" maxLength={40} placeholder="Código, ex.: CANIL" className="rounded-lg border border-slate-300 p-3 text-sm"/></div><textarea name="description" maxLength={500} rows={2} placeholder="Descrição" className="rounded-lg border border-slate-300 p-3 text-sm"/><button className="w-fit rounded-lg bg-[#092940] px-5 py-2.5 text-sm font-bold text-white">Criar grupamento</button></form>
 </div>;
}