import { requireAdmin } from "../../../lib/auth/require-admin";
import { createAdminClient } from "../../../lib/supabase/admin";
import { createUnit,removeMember,saveCategoryRoute,saveMember } from "./actions";

export default async function UnitsPage(){
 await requireAdmin();const admin=createAdminClient();
 const [{data:units},{data:members},{data:profiles},{data:categories},{data:routes}]=await Promise.all([
  admin.from("vortex_units").select("*").order("is_default",{ascending:false}).order("name"),
  admin.from("vortex_unit_members").select("unit_id,profile_id,member_role,can_triage"),
  admin.from("vortex_profiles").select("id,full_name,role,active,functional_title").eq("active",true).in("role",["COORDENADOR","OPERADOR"]).order("full_name"),
  admin.from("vortex_categories").select("id,name,active").eq("active",true).order("sort_order").order("name"),
  admin.from("vortex_category_routes").select("category_id,unit_id").eq("active",true),
 ]);
 const profileMap=new Map((profiles??[]).map(p=>[p.id,p]));const routeMap=new Map((routes??[]).map(r=>[r.category_id,r.unit_id]));
 return <div className="max-w-6xl"><p className="text-xs font-bold tracking-[.16em] text-[#0c766d]">ESTRUTURA OPERACIONAL</p><h1 className="mt-2 text-3xl font-bold">Grupamentos e triagem</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Organize coordenadores e inspetores por grupamento. As categorias podem ser direcionadas automaticamente para a unidade responsável; a permissão de triagem geral permite corrigir o destino quando necessário.</p>

 <section className="mt-7 grid gap-4 lg:grid-cols-2">{(units??[]).map(unit=>{const unitMembers=(members??[]).filter(m=>m.unit_id===unit.id);return <article key={unit.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{unit.name}</h2><p className="mt-1 text-xs font-bold text-[#0c766d]">{unit.code}</p></div>{unit.is_default&&<span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">Padrão</span>}</div><p className="mt-3 text-sm leading-6 text-slate-600">{unit.description||"Sem descrição."}</p><div className="mt-4 grid gap-2">{unitMembers.map(m=>{const p=profileMap.get(m.profile_id);return <div key={m.profile_id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-3"><div><p className="text-sm font-bold">{p?.full_name||"Usuário"}</p><p className="text-xs text-slate-500">{m.member_role==="COORDENADOR"?"Coordenador":"Inspetor/atendente"}{m.can_triage?" · Triagem geral":""}</p></div><form action={removeMember}><input type="hidden" name="unitId" value={unit.id}/><input type="hidden" name="profileId" value={m.profile_id}/><button className="text-xs font-bold text-red-700">Remover</button></form></div>})}</div>
 <form action={saveMember} className="mt-4 grid gap-2 border-t border-slate-100 pt-4 sm:grid-cols-2"><input type="hidden" name="unitId" value={unit.id}/><select name="memberRole" className="rounded-lg border border-slate-300 p-2.5 text-sm"><option value="COORDENADOR">Coordenador</option><option value="INSPETOR">Inspetor/atendente</option></select><select name="profileId" required className="rounded-lg border border-slate-300 p-2.5 text-sm"><option value="">Selecionar usuário</option>{(profiles??[]).map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select><label className="flex items-center gap-2 text-xs text-slate-600"><input name="canTriage" type="checkbox"/> Permitir triagem geral</label><button className="rounded-lg bg-[#0c766d] px-3 py-2 text-sm font-bold text-white">Adicionar/atualizar</button></form></article>})}</section>

 <section className="mt-8 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Regras automáticas por categoria</h2><p className="mt-1 text-sm text-slate-600">Ao receber uma denúncia, o sistema envia a categoria ao grupamento definido. Sem regra, ela vai para o Grupo Operacional.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{(categories??[]).map(category=><form action={saveCategoryRoute} key={category.id} className="rounded-lg border border-slate-200 p-3"><input type="hidden" name="categoryId" value={category.id}/><p className="text-sm font-bold">{category.name}</p><div className="mt-2 flex gap-2"><select name="unitId" defaultValue={routeMap.get(category.id)||""} className="min-w-0 flex-1 rounded-lg border border-slate-300 p-2 text-sm"><option value="">Grupo Operacional (padrão)</option>{(units??[]).filter(u=>!u.is_default&&u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button className="rounded-lg border border-[#0c766d] px-3 text-xs font-bold text-[#0c766d]">Salvar</button></div></form>)}</div></section>

 <form action={createUnit} className="mt-8 grid gap-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Novo grupamento</h2><div className="grid gap-3 sm:grid-cols-2"><input required name="name" maxLength={120} placeholder="Nome do grupamento" className="rounded-lg border border-slate-300 p-3 text-sm"/><input required name="code" maxLength={40} placeholder="Código, ex.: CANIL" className="rounded-lg border border-slate-300 p-3 text-sm"/></div><textarea name="description" maxLength={500} rows={2} placeholder="Descrição" className="rounded-lg border border-slate-300 p-3 text-sm"/><button className="w-fit rounded-lg bg-[#092940] px-5 py-2.5 text-sm font-bold text-white">Criar grupamento</button></form>
 </div>;
}
