"use client";
import { useEffect,useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { BrandMark } from "../components/brand-mark";
import { createClient } from "../../lib/supabase/client";
export default function ResetPasswordPage(){
 const router=useRouter();const [ready,setReady]=useState(false),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void createClient().auth.getUser().then(({data})=>setReady(Boolean(data.user)));},[]);
 async function submit(e:FormEvent){e.preventDefault();if(password.length<10){setMessage("A senha deve ter pelo menos 10 caracteres.");return}if(password!==confirm){setMessage("A confirmação da senha não confere.");return}setBusy(true);const supabase=createClient();const {error}=await supabase.auth.updateUser({password});if(error){setMessage("O link pode ter expirado. Solicite uma nova recuperação.");setBusy(false);return}await supabase.auth.signOut();router.replace("/login?recovery=success");router.refresh();}
 return <main className="min-h-screen bg-[#f4f7f8] text-[#102b42]"><header className="bg-[#092940]"><div className="mx-auto max-w-6xl px-5 py-4"><BrandMark /></div></header><div className="mx-auto flex max-w-md px-5 py-14"><form onSubmit={submit} className="w-full rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8"><p className="text-xs font-bold tracking-[.16em] text-[#0c766d]">NOVA SENHA</p><h1 className="mt-2 text-3xl font-bold">Redefinir senha</h1>{!ready?<p className="mt-5 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Validando o link de recuperação...</p>:<><label className="mt-7 block text-sm font-semibold">Nova senha<input required minLength={10} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3" /></label><label className="mt-4 block text-sm font-semibold">Confirmar nova senha<input required minLength={10} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3" /></label>{message&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>}<button disabled={busy} className="mt-6 min-h-11 w-full rounded-lg bg-[#0c766d] text-sm font-bold text-white disabled:opacity-60">{busy?"Salvando...":"Definir nova senha"}</button></>}</form></div></main>;
}
