"use client";

import Link from "next/link";
import { useState } from "react";
import { BrandMark } from "../components/brand-mark";
import { FileText, Shield } from "../components/icons";

const fieldClass = "mt-2 w-full rounded-lg border border-slate-300 bg-white px-3.5 py-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-[#0c766d] focus:ring-2 focus:ring-[#0c766d]/15";

export function FollowUp() {
  const [protocol, setProtocol] = useState(""); const [code, setCode] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState("");
  const consult = () => { if (!protocol.trim() || !code.trim()) { setError("Informe o protocolo e o código de acompanhamento."); setShow(false); return; } setError(""); setShow(true); };
  return <main className="min-h-screen bg-[#f4f7f8] text-[#102b42]"><header className="bg-[#092940]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8 lg:px-10"><BrandMark /><Link href="/" className="text-sm font-semibold text-slate-200 hover:text-white">Voltar ao início</Link></div></header><div className="mx-auto max-w-5xl px-5 py-10 sm:px-8 sm:py-14"><div className="max-w-2xl"><p className="text-xs font-bold tracking-[.16em] text-[#0c766d]">CONSULTA DE DENÚNCIA</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Acompanhe seu registro</h1><p className="mt-3 leading-7 text-slate-600">Informe os dados recebidos ao concluir uma denúncia para consultar seu andamento.</p></div><div className="mt-8 grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={(event) => { event.preventDefault(); consult(); }} className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div><label htmlFor="protocol" className="text-sm font-semibold text-slate-700">Protocolo</label><input id="protocol" value={protocol} onChange={(event) => setProtocol(event.target.value)} className={fieldClass} placeholder="Ex.: VTX-2026-8F4D" /></div><div className="mt-5"><label htmlFor="code" className="text-sm font-semibold text-slate-700">Código de acompanhamento</label><input id="code" value={code} onChange={(event) => setCode(event.target.value)} className={fieldClass} placeholder="Ex.: K7P9-42M" /></div>{error && <p role="alert" className="mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-800">{error}</p>}<button type="submit" className="mt-6 min-h-11 w-full rounded-lg bg-[#0c766d] px-5 text-sm font-bold text-white hover:bg-[#095f58]">Consultar</button><p className="mt-4 flex gap-2 text-xs leading-5 text-slate-500"><Shield /> Nesta etapa, a consulta é uma demonstração visual e não acessa registros reais.</p></form><div>{show ? <DemoResult protocol={protocol} /> : <EmptyState />}</div></div></div></main>;
}
function EmptyState() { return <section className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white/60 p-8 text-center"><span className="grid size-12 place-items-center rounded-full bg-[#d8f1ed] text-[#0c766d]"><FileText /></span><h2 className="mt-4 text-lg font-bold">Aguardando consulta</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-600">O andamento demonstrativo aparecerá aqui após preencher os dados ao lado.</p></section>; }
function DemoResult({ protocol }: { protocol: string }) { return <section className="rounded-2xl border border-[#0c766d]/25 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-start"><div><p className="text-xs font-bold tracking-[.14em] text-[#0c766d]">DEMONSTRAÇÃO DE ACOMPANHAMENTO</p><h2 className="mt-2 text-xl font-bold">Registro {protocol.toUpperCase()}</h2></div><span className="w-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">EM ANÁLISE</span></div><p className="mt-5 rounded-lg bg-[#d8f1ed]/50 p-4 text-sm leading-6 text-slate-700">Esta visualização demonstra como as atualizações serão apresentadas após a conexão segura com a base de dados.</p><ol className="mt-6 space-y-6 border-l border-slate-200 pl-5"><Timeline title="Registro recebido" text="Sua informação foi registrada e recebeu protocolo de acompanhamento." date="Hoje, 10:32" active /><Timeline title="Em análise" text="A equipe responsável está avaliando as informações fornecidas." date="Hoje, 10:45" active /><Timeline title="Encaminhamento" text="Uma atualização aparecerá aqui quando houver providência permitida para consulta." date="Aguardando" /></ol></section>; }
function Timeline({ title, text, date, active = false }: { title: string; text: string; date: string; active?: boolean }) { return <li className="relative"><span className={`absolute -left-[29px] top-1 size-3 rounded-full ring-4 ring-white ${active ? "bg-[#0c766d]" : "bg-slate-300"}`} /><div className="flex flex-col gap-1 sm:flex-row sm:justify-between"><h3 className="font-bold">{title}</h3><time className="text-xs text-slate-500">{date}</time></div><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></li>; }
