"use client";
import { useState,useTransition } from "react";
import { assignReport,returnToDirectorate,routeReport,setOperationalPriority } from "./assignment-actions";
import { formatAssignedAt,roleLabel } from "../../presentation";
type Profile={id:string;full_name:string|null;role?:string;functional_title?:string|null};
type Assignment={assigned_to:string;assigned_at:string;assignee:Profile|null}|null;
type Unit={id:string;name:string};

export function AssignmentPanel({reportId,assignment,profiles,canManage,unitId,unitName,units,canRoute,canReturn,operationalPriority}:{reportId:string;assignment:Assignment;profiles:Profile[];canManage:boolean;unitId:string|null;unitName:string;units:Unit[];canRoute:boolean;canReturn:boolean;operationalPriority?:string|null}){
 const [selected,setSelected]=useState(assignment?.assigned_to||""),[selectedUnit,setSelectedUnit]=useState(unitId||""),[priority,setPriority]=useState(operationalPriority||""),[reason,setReason]=useState(""),[message,setMessage]=useState(""),[pending,startTransition]=useTransition();const current=assignment?.assignee;
 return <section id="encaminhamento" className="scroll-mt-24 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Encaminhamento e responsável</h2>
 <div className="mt-3 grid gap-3 rounded-lg bg-slate-50 p-3 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Grupamento responsável</p><p className="mt-1 font-bold">{unitName||"Não definido"}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Prioridade operacional</p><p className="mt-1 font-bold">{priority==="HIGH"?"Alta":priority==="MEDIUM"?"Média":priority==="LOW"?"Baixa":"Ainda não definida"}</p></div></div>
 {canRoute&&<div className="mt-4 rounded-lg border border-slate-200 p-4"><p className="text-sm font-bold">Classificação da Diretoria</p><p className="mt-1 text-xs leading-5 text-slate-500">A urgência indicada pelo cidadão continua registrada separadamente. Defina aqui a prioridade operacional da GCMJP.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><select value={priority} onChange={e=>setPriority(e.target.value)} className="min-h-11 flex-1 rounded-lg border border-slate-300 px-3 text-sm"><option value="">Selecionar prioridade</option><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option></select><button disabled={!priority||priority===operationalPriority||pending} onClick={()=>startTransition(async()=>{const result=await setOperationalPriority(reportId,priority);setMessage(result.error||result.message||"");})} className="rounded-lg border border-[#0c766d] px-4 py-2 text-sm font-bold text-[#0c766d] disabled:opacity-40">Salvar prioridade</button></div></div>}
 {canRoute&&<div className="mt-4"><label className="text-sm font-semibold">Triagem: encaminhar para a chefia/coordenação<select value={selectedUnit} onChange={e=>setSelectedUnit(e.target.value)} className="mt-2 w-full rounded-lg border p-3 text-sm"><option value="">Selecione o grupamento</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><button disabled={!selectedUnit||selectedUnit===unitId||pending} onClick={()=>startTransition(async()=>{const result=await routeReport(reportId,selectedUnit);setMessage(result.error||result.message||"");})} className="mt-2 rounded-lg border border-[#0c766d] px-4 py-2 text-sm font-bold text-[#0c766d] disabled:opacity-40">{unitId?"Redirecionar grupamento":"Encaminhar grupamento"}</button></div>}
 <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Agente / operador / inspetor responsável</p>{current?<p className="mt-2 text-sm"><b>{current.full_name||"Sem nome"}</b>{current.functional_title&&<> · {current.functional_title}</>}<br/>{current.role&&roleLabel(current.role)}<br/><span className="text-slate-500">Atribuído em {formatAssignedAt(assignment!.assigned_at)}</span></p>:<p className="mt-2 text-sm text-slate-600">A chefia/coordenação ainda não atribuiu um responsável individual.</p>}
 {canManage&&<div className="mt-4"><label className="text-sm font-semibold">Distribuir para integrante do grupamento<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-lg border p-3 text-sm"><option value="">Selecione um agente, operador ou inspetor</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||"Sem nome"}{p.functional_title?` · ${p.functional_title}`:""}</option>)}</select></label><button disabled={!selected||pending} onClick={()=>startTransition(async()=>{const result=await assignReport(reportId,selected);setMessage(result.error||result.message||"");})} className="mt-3 min-h-10 rounded-lg bg-[#0c766d] px-4 text-sm font-bold text-white disabled:opacity-60">{pending?"Salvando...":"Atribuir responsável"}</button></div>}</div>
 {canReturn&&unitId&&<div className="mt-5 border-t border-amber-200 pt-4"><p className="text-sm font-bold text-amber-900">Direcionamento incorreto?</p><p className="mt-1 text-xs leading-5 text-slate-600">Devolva a denúncia para a Diretoria Operacional realizar uma nova triagem. A justificativa ficará registrada no histórico.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} rows={3} placeholder="Informe o motivo da devolução..." className="mt-3 w-full rounded-lg border border-amber-300 p-3 text-sm"/><button disabled={pending||reason.trim().length<5} onClick={()=>startTransition(async()=>{const result=await returnToDirectorate(reportId,reason);setMessage(result.error||result.message||"");if(!result.error)setReason("");})} className="mt-2 rounded-lg border border-amber-600 px-4 py-2.5 text-sm font-bold text-amber-800 disabled:opacity-40">Devolver para nova triagem</button></div>}
 {message&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{message}</p>}</section>;
}
