"use client";
import { useState,useTransition } from "react";
import { assignReport,routeReport } from "./assignment-actions";
import { formatAssignedAt,roleLabel } from "../../presentation";
type Profile={id:string;full_name:string|null;role?:string;functional_title?:string|null};
type Assignment={assigned_to:string;assigned_at:string;assignee:Profile|null}|null;
type Unit={id:string;name:string};
export function AssignmentPanel({reportId,assignment,profiles,canManage,unitId,unitName,units,canRoute}:{reportId:string;assignment:Assignment;profiles:Profile[];canManage:boolean;unitId:string|null;unitName:string;units:Unit[];canRoute:boolean}){
 const [selected,setSelected]=useState(assignment?.assigned_to||""),[selectedUnit,setSelectedUnit]=useState(unitId||""),[message,setMessage]=useState(""),[pending,startTransition]=useTransition();const current=assignment?.assignee;
 return <section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Triagem e responsável</h2><div className="mt-3 rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Grupamento responsável</p><p className="mt-1 font-bold">{unitName||"Não definido"}</p></div>
 {canRoute&&<div className="mt-4"><label className="text-sm font-semibold">Encaminhar para outro grupamento<select value={selectedUnit} onChange={e=>setSelectedUnit(e.target.value)} className="mt-2 w-full rounded-lg border p-3 text-sm">{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><button disabled={!selectedUnit||selectedUnit===unitId||pending} onClick={()=>startTransition(async()=>{const result=await routeReport(reportId,selectedUnit);setMessage(result.error||result.message||"");})} className="mt-2 rounded-lg border border-[#0c766d] px-4 py-2 text-sm font-bold text-[#0c766d] disabled:opacity-40">Alterar grupamento</button></div>}
 <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Inspetor/atendente</p>{current?<p className="mt-2 text-sm"><b>{current.full_name||"Sem nome"}</b>{current.functional_title&&<> · {current.functional_title}</>}<br/>{current.role&&roleLabel(current.role)}<br/><span className="text-slate-500">Atribuído em {formatAssignedAt(assignment!.assigned_at)}</span></p>:<p className="mt-2 text-sm text-slate-600">Ainda não atribuída.</p>}
 {canManage&&<div className="mt-4"><label className="text-sm font-semibold">Atribuir responsável<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-lg border p-3 text-sm"><option value="">Selecione um inspetor/atendente do grupamento</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||"Sem nome"}{p.functional_title?` · ${p.functional_title}`:""}</option>)}</select></label><button disabled={!selected||pending} onClick={()=>startTransition(async()=>{const result=await assignReport(reportId,selected);setMessage(result.error||result.message||"");})} className="mt-3 min-h-10 rounded-lg bg-[#0c766d] px-4 text-sm font-bold text-white disabled:opacity-60">{pending?"Salvando...":"Atribuir responsável"}</button></div>}</div>
 {message&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{message}</p>}</section>;
}
