"use client";
import { useState, useTransition } from "react";
import { addInternalNote, sendReporterMessage, updateReportStatus } from "./workflow-actions";
import { statusLabel } from "../../presentation";

const statuses = ["NOVA","EM_ANALISE","ENCAMINHADA","EM_ATENDIMENTO","CONCLUIDA","IMPROCEDENTE"];

export function WorkflowPanel({ reportId, currentStatus }: { reportId: string; currentStatus: string }) {
  const [status,setStatus]=useState(currentStatus); const [note,setNote]=useState(""); const [internal,setInternal]=useState(""); const [message,setMessage]=useState(""); const [feedback,setFeedback]=useState(""); const [pending,startTransition]=useTransition();
  const run=(fn:()=>Promise<{error?:string;message?:string}>)=>startTransition(async()=>{setFeedback("");const r=await fn();setFeedback(r.error||r.message||"");});
  return <div className="grid gap-5 xl:grid-cols-2">
    <section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Andamento da denúncia</h2><p className="mt-1 text-sm text-slate-500">Atualize a situação e registre o motivo da alteração.</p><div className="mt-4 grid gap-3"><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border border-slate-300 p-3 text-sm">{statuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} maxLength={1000} placeholder="Observação sobre a alteração (opcional)" className="rounded-lg border border-slate-300 p-3 text-sm" /><button disabled={pending||status===currentStatus} onClick={()=>run(()=>updateReportStatus(reportId,status,note))} className="min-h-11 rounded-lg bg-[#0c766d] px-4 text-sm font-bold text-white disabled:opacity-50">Atualizar status</button></div><div className="mt-6 border-t pt-5"><p className="text-sm font-bold">Observação interna</p><textarea value={internal} onChange={e=>setInternal(e.target.value)} rows={3} maxLength={1500} placeholder="Registre uma informação operacional no histórico..." className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm" /><button disabled={pending||internal.trim().length<3} onClick={()=>run(async()=>{const r=await addInternalNote(reportId,internal);if(!r.error)setInternal("");return r;})} className="mt-2 rounded-lg border border-[#0c766d] px-4 py-2.5 text-sm font-bold text-[#0c766d] disabled:opacity-50">Registrar observação</button></div>{feedback&&<p className="mt-4 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{feedback}</p>}</section>
    <section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Comunicação com o denunciante</h2><p className="mt-1 text-sm text-slate-500">A mensagem ficará disponível no acompanhamento pelo protocolo.</p><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={6} maxLength={2000} placeholder="Ex.: Sua denúncia foi encaminhada para análise da equipe responsável." className="mt-4 w-full rounded-lg border border-slate-300 p-3 text-sm" /><div className="mt-2 flex items-center justify-between gap-3"><span className="text-xs text-slate-400">{message.length}/2000</span><button disabled={pending||message.trim().length<2} onClick={()=>run(async()=>{const r=await sendReporterMessage(reportId,message);if(!r.error)setMessage("");return r;})} className="rounded-lg bg-[#102b42] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Enviar mensagem</button></div></section>
  </div>;
}
