"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { BrandMark } from "../components/brand-mark";
import { createClient } from "../../lib/supabase/client";

export function LoginForm() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); const supabase = createClient(); const { data, error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError || !data.user) { setError("Não foi possível validar suas credenciais."); setLoading(false); return; } const { data: profile } = await supabase.from("vortex_profiles").select("active").eq("id", data.user.id).maybeSingle(); if (!profile?.active) { await supabase.auth.signOut(); setError("Seu acesso não está autorizado para a área operacional."); setLoading(false); return; } router.replace("/admin"); router.refresh(); };
  return <main className="min-h-screen bg-[#f4f7f8] text-[#102b42]"><header className="bg-[#092940]"><div className="mx-auto max-w-6xl px-5 py-4"><BrandMark /></div></header><div className="mx-auto flex max-w-md px-5 py-14"><form onSubmit={submit} className="w-full rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8"><p className="text-xs font-bold tracking-[.16em] text-[#0c766d]">ÁREA RESTRITA</p><h1 className="mt-2 text-3xl font-bold">Acesso da equipe</h1><p className="mt-3 text-sm leading-6 text-slate-600">Uso exclusivo da equipe da Guarda Civil Municipal de João Pessoa.</p><label className="mt-7 block text-sm font-semibold">E-mail<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 outline-none focus:border-[#0c766d]" /></label><label className="mt-5 block text-sm font-semibold">Senha<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 outline-none focus:border-[#0c766d]" /></label>{error && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button disabled={loading} className="mt-6 min-h-11 w-full rounded-lg bg-[#0c766d] text-sm font-bold text-white disabled:opacity-60">{loading ? "Entrando..." : "Entrar"}</button><Link href="/" className="mt-5 block text-center text-sm font-semibold text-[#0c766d]">Voltar ao início</Link></form></div></main>;
}
