"use client";

type AttachmentView = { original_name?: string | null; mime_type?: string | null; size_bytes?: number | null; backup_file?: string | null; storage_deleted_at?: string | null };
type ReportView = {
  id:string; protocol:string; status:string; urgency:string; resolution?:string|null; description:string;
  address?:string|null; neighborhood?:string|null; reference_point?:string|null; latitude?:number|null; longitude?:number|null;
  event_at?:string|null; created_at:string; updated_at:string; vortex_categories?:{name?:string}|Array<{name?:string}>|null;
  attachments:AttachmentView[]; history:Array<Record<string,unknown>>; messages:Array<Record<string,unknown>>;
  assignments?:Array<Record<string,unknown>>;
};

const status:Record<string,string>={NOVA:"Nova",EM_ANALISE:"Em análise",EM_ATENDIMENTO:"Em atendimento",FINALIZADA:"Finalizada"};
const urgency:Record<string,string>={LOW:"Baixa",MEDIUM:"Média",HIGH:"Alta"};
const resolution:Record<string,string>={PROCEDENTE:"Procedente",IMPROCEDENTE:"Improcedente",RESOLVIDA:"Resolvida",ENCAMINHADA_OUTRO_ORGAO:"Encaminhada a outro órgão",NAO_FOI_POSSIVEL_AVERIGUAR:"Não foi possível averiguar"};

function e(value:unknown){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function date(value:unknown){if(!value)return"Não informado";const d=new Date(String(value));return Number.isNaN(d.getTime())?e(value):d.toLocaleString("pt-BR");}
function cat(r:ReportView){return Array.isArray(r.vortex_categories)?r.vortex_categories[0]?.name??"Não informada":r.vortex_categories?.name??"Não informada";}
function bytes(n:number|null|undefined){const v=Number(n??0);if(v>=1048576)return `${(v/1048576).toFixed(1)} MB`;if(v>=1024)return `${(v/1024).toFixed(1)} KB`;return `${v} B`;}
function val(v:unknown){return v===null||v===undefined||v===""?"Não informado":e(v);}
function sender(v:unknown){return v==="STAFF"?"Equipe VÓRTEX":v==="REPORTER"?"Denunciante":"Sistema";}

export function offlineBackupCss(){return `
:root{font-family:Arial,Helvetica,sans-serif;color:#102b42;background:#f3f6f7}*{box-sizing:border-box}body{margin:0;background:#f3f6f7}.top{background:#092940;color:#fff;padding:22px 0}.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.brand{font-size:22px;font-weight:800;letter-spacing:.08em}.muted{color:#64748b}.top .muted{color:#cbd5e1}.hero{padding:30px 0 18px}.grid{display:grid;gap:14px}.stats{grid-template-columns:repeat(auto-fit,minmax(160px,1fr))}.card{background:#fff;border:1px solid #dbe4e8;border-radius:12px;padding:18px;box-shadow:0 2px 8px #102b4210}.stat b{display:block;font-size:28px;margin-top:6px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.toolbar input,.toolbar select{padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;min-width:210px}.reports{display:grid;gap:12px;margin-bottom:40px}.report{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center;text-decoration:none;color:inherit}.report:hover{border-color:#0c766d}.tag{display:inline-block;padding:5px 9px;border-radius:999px;background:#e9f7f5;color:#0c766d;font-size:12px;font-weight:700;margin-right:6px}.tag.high{background:#fee2e2;color:#991b1b}.meta{font-size:13px;color:#64748b;margin-top:7px}.section{margin:18px 0}.section h2{font-size:18px;margin:0 0 10px}.kv{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.kv div{background:#f8fafc;border-radius:8px;padding:10px}.kv b{display:block;font-size:12px;color:#64748b;margin-bottom:4px}.description{white-space:pre-wrap;line-height:1.65}.timeline{border-left:3px solid #d8f1ed;padding-left:16px}.event{margin:0 0 14px}.event p{margin:4px 0}.message{border-left:4px solid #0c766d;background:#f8fafc;padding:12px;margin:10px 0;border-radius:0 8px 8px 0}.gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}.gallery a{text-decoration:none;color:inherit}.gallery img{width:100%;height:150px;object-fit:cover;border-radius:8px;border:1px solid #dbe4e8}.back{display:inline-block;margin:18px 0;color:#0c766d;font-weight:700;text-decoration:none}.footer{padding:25px 0 40px;color:#64748b;font-size:12px}@media(max-width:640px){.report{grid-template-columns:1fr}.wrap{width:min(100% - 20px,1120px)}}`; }

export function offlineIndexHtml(reports:ReportView[], generatedAt:string, month:string, part:number, totalParts:number){
  const rows=reports.map(r=>{const year=new Date(r.created_at).getFullYear();const folder=`denuncias/${year}/${encodeURIComponent(r.protocol)}/index.html`;return `<a class="card report" data-search="${e((r.protocol+" "+cat(r)+" "+(r.neighborhood??"")+" "+r.description).toLowerCase())}" data-status="${e(r.status)}" href="${folder}"><div><div><span class="tag">${e(status[r.status]??r.status)}</span><span class="tag ${r.urgency==="HIGH"?"high":""}">Urgência ${e(urgency[r.urgency]??r.urgency)}</span></div><h3>${e(r.protocol)} · ${e(cat(r))}</h3><div class="meta">${e(r.neighborhood||"Bairro não informado")} · ${date(r.created_at)} · ${r.attachments.length} anexo(s)</div></div><strong>Abrir →</strong></a>`;}).join("");
  const script=`const q=document.getElementById('q'),s=document.getElementById('s'),rows=[...document.querySelectorAll('.report')];function f(){const x=q.value.toLowerCase().trim(),st=s.value;rows.forEach(r=>r.style.display=(!x||r.dataset.search.includes(x))&&(!st||r.dataset.status===st)?'grid':'none')}q.addEventListener('input',f);s.addEventListener('change',f);`;
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Backup VÓRTEX ${e(month)}</title><link rel="stylesheet" href="assets/backup.css"></head><body><header class="top"><div class="wrap"><div class="brand">VÓRTEX</div><div class="muted">Visualizador offline de backup administrativo</div></div></header><main class="wrap"><section class="hero"><h1>Backup de denúncias — ${e(month)}</h1><p class="muted">Parte ${part} de ${totalParts} · gerado em ${date(generatedAt)}. Este painel funciona offline após a extração do ZIP.</p></section><section class="grid stats"><div class="card stat">Denúncias<b>${reports.length}</b></div><div class="card stat">Anexos<b>${reports.reduce((n,r)=>n+r.attachments.filter(a=>a.backup_file).length,0)}</b></div><div class="card stat">Finalizadas<b>${reports.filter(r=>r.status==="FINALIZADA").length}</b></div><div class="card stat">Alta urgência<b>${reports.filter(r=>r.urgency==="HIGH").length}</b></div></section><div class="toolbar"><input id="q" type="search" placeholder="Buscar protocolo, categoria, bairro..."><select id="s"><option value="">Todos os status</option><option value="NOVA">Nova</option><option value="EM_ANALISE">Em análise</option><option value="EM_ATENDIMENTO">Em atendimento</option><option value="FINALIZADA">Finalizada</option></select></div><section class="reports">${rows}</section></main><footer class="wrap footer">Cópia administrativa offline do VÓRTEX. Trate este conteúdo como informação institucional sensível.</footer><script>${script}</script></body></html>`;
}

export function offlineReportHtml(r:ReportView){
  const hist=r.history.map(h=>`<div class="event"><b>${date(h.created_at)}</b><p>${e(status[String(h.old_status)]??h.old_status??"Início")} → ${e(status[String(h.new_status)]??h.new_status)}</p>${h.note?`<p class="muted">${e(h.note)}</p>`:""}</div>`).join("")||"<p class='muted'>Sem histórico.</p>";
  const msgs=r.messages.map(m=>`<div class="message"><b>${e(sender(m.sender_type))}</b><div class="meta">${date(m.created_at)}</div><p class="description">${e(m.message)}</p></div>`).join("")||"<p class='muted'>Sem mensagens.</p>";
  const ass=(r.assignments??[]).map(a=>`<div class="event"><b>${date(a.assigned_at)}</b><p>Responsável: ${e(a.assigned_to_name??a.assigned_to??"Não informado")}</p>${a.ended_at?`<p class="muted">Encerrada em ${date(a.ended_at)}</p>`:"<p class='muted'>Atribuição ativa no momento do backup</p>"}</div>`).join("")||"<p class='muted'>Sem atribuições registradas.</p>";
  const imgs=r.attachments.filter(a=>a.backup_file).map(a=>`<a href="${e(a.backup_file)}" target="_blank"><img src="${e(a.backup_file)}" alt="${e(a.original_name??"Anexo")}"><div class="meta">${e(a.original_name??"Imagem")} · ${bytes(a.size_bytes)}</div></a>`).join("")||"<p class='muted'>Nenhuma imagem disponível neste ZIP.</p>";
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(r.protocol)} — VÓRTEX</title><link rel="stylesheet" href="../../../assets/backup.css"></head><body><header class="top"><div class="wrap"><div class="brand">VÓRTEX</div><div class="muted">Registro de denúncia — cópia offline</div></div></header><main class="wrap"><a class="back" href="../../../index.html">← Voltar ao painel</a><section class="card"><div><span class="tag">${e(status[r.status]??r.status)}</span><span class="tag ${r.urgency==="HIGH"?"high":""}">Urgência ${e(urgency[r.urgency]??r.urgency)}</span></div><h1>${e(r.protocol)}</h1><p class="muted">${e(cat(r))}</p>${r.resolution?`<p><b>Resultado:</b> ${e(resolution[r.resolution]??r.resolution)}</p>`:""}<section class="section"><h2>Dados da denúncia</h2><div class="kv"><div><b>Registrada em</b>${date(r.created_at)}</div><div><b>Fato ocorrido em</b>${date(r.event_at)}</div><div><b>Bairro</b>${val(r.neighborhood)}</div><div><b>Endereço</b>${val(r.address)}</div><div><b>Ponto de referência</b>${val(r.reference_point)}</div><div><b>Coordenadas</b>${r.latitude!=null&&r.longitude!=null?`${e(r.latitude)}, ${e(r.longitude)}`:"Não informadas"}</div></div></section><section class="section"><h2>Descrição</h2><div class="description">${e(r.description)}</div></section><section class="section"><h2>Anexos</h2><div class="gallery">${imgs}</div></section><section class="section"><h2>Histórico</h2><div class="timeline">${hist}</div></section><section class="section"><h2>Atribuições</h2><div class="timeline">${ass}</div></section><section class="section"><h2>Mensagens</h2>${msgs}</section></section></main><footer class="wrap footer">Arquivo gerado pelo VÓRTEX para consulta administrativa offline.</footer></body></html>`;
}
